In [1]:
from datapreparation.data_preparation import Data_Preparation as dp
import pandas as pd
prep = dp()
X_train, X_val, X_test, y_train, y_val, y_test = prep.train_val_test_split_64_16_20_func(func= prep.prepare_data_pump_time_v2)
X_train

,hours_since_watering,soil_deficit_ratio,deficit_x_light,deficit_x_temp,deficit_x_air,et_approx
4105,273.0,0.768786,-3.230439,NaN,-2.429364,NaN
2730,182.0,0.091826,NaN,-0.247012,-0.604216,NaN
84024,83.0,0.562348,-2.303659,-0.073105,1.591445,0.714663
106895,133.0,0.182957,-0.054430,-0.064035,-0.934908,5.175905
8842,589.0,-0.017949,0.049188,0.052231,0.068026,0.283182
...,...,...,...,...,...,...
62835,219.0,0.341353,-0.661372,0.314045,-0.559820,2.006201
90812,2.0,0.220000,-0.397760,0.096800,-0.358600,4.092834
74102,31.0,0.216772,-0.281912,0.567943,0.351171,5.128716
75779,206.0,NaN,NaN,NaN,NaN,5.392630
38995,1850.0,0.118354,-0.023257,0.029589,NaN,NaN

In [2]:
from sklearn.impute import KNNImputer

imputer = KNNImputer(n_neighbors=5, weights='distance')

X_train_imputed = imputer.fit_transform(X_train)

X_train_imputed = pd.DataFrame(
    X_train_imputed,
    columns=X_train.columns,
    index=X_train.index
)

In [3]:
X_val_imputed = imputer.transform(X_val)
X_test_imputed = imputer.transform(X_test)

X_val_imputed = pd.DataFrame(
    X_val_imputed,
    columns=X_val.columns,
    index=X_val.index
)
X_test_imputed = pd.DataFrame(
    X_test_imputed,
    columns=X_test.columns,
    index=X_test.index
)
X_test_imputed

,hours_since_watering,soil_deficit_ratio,deficit_x_light,deficit_x_temp,deficit_x_air,et_approx
20928,135.0,0.394486,0.268251,-0.114401,-0.311644,5.400998
107419,117.0,0.305249,-0.047691,-0.423905,-0.911429,2.691243
41278,71.0,0.406634,-0.910453,-0.378170,-0.618084,0.000000
119396,32.0,0.398496,0.569850,0.187293,1.056015,5.750309
78091,75.0,0.199051,-0.707326,-0.007962,-0.494449,3.000649
...,...,...,...,...,...,...
31193,63.0,0.398496,-0.802173,-0.932481,-0.195263,0.000000
111514,331.0,0.172348,-0.571333,-0.475680,-0.243010,0.000000
66845,69.0,0.208696,-0.347947,0.252522,0.298435,1.801856
119041,6.0,0.360660,-0.373644,-0.490733,-0.567485,5.434638
24533,1635.0,0.034457,0.005582,-0.018262,0.061334,5.321621

In [4]:
import optuna
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error
import warnings
warnings.filterwarnings("ignore")


def objective(trial):
    params = {
        "n_estimators": trial.suggest_int("n_estimators", 200, 1200),
        "max_depth": trial.suggest_int("max_depth", 4, 12),
        "min_samples_split": trial.suggest_int("min_samples_split", 2, 12),
        "min_samples_leaf": trial.suggest_int("min_samples_leaf", 1, 8),
        "max_features": trial.suggest_categorical("max_features", ["sqrt", "log2", None]),
        "bootstrap": trial.suggest_categorical("bootstrap", [True, False]),

        "random_state": 42,
        "n_jobs": -1,
    }

    model = RandomForestRegressor(**params)

    model.fit(X_train_imputed, y_train)

    val_pred = model.predict(X_val_imputed)
    val_mae = mean_absolute_error(y_val, val_pred)

    return val_mae

study = optuna.create_study(
    direction="minimize",
    pruner=optuna.pruners.MedianPruner(n_warmup_steps=10),
    sampler= optuna.samplers.TPESampler(seed=42, multivariate=True,group=True,n_startup_trials=50)
)
study.optimize(objective, n_trials=60, show_progress_bar=True)

print("Best Trial:", study.best_trial.number)
print("Best MAE:", study.best_value)
print("Best Parameters:")
for key, value in study.best_params.items():
    print(f"    {key}: {value}")

best_params = study.best_params
best_params.update({
    "random_state": 42,
    "n_jobs": -1,
})

final_model = RandomForestRegressor(**best_params)
final_model.fit(X_train_imputed, y_train)

[I 2026-05-18 08:26:13,469] A new study created in memory with name: no-name-0b22c5db-7be8-4d01-b89a-7a63ac19c83c

  0%|          | 0/60 [00:00<?, ?it/s]

[I 2026-05-18 08:26:18,292] Trial 0 finished with value: 0.8221838176281153 and parameters: {'n_estimators': 574, 'max_depth': 12, 'min_samples_split': 10, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 0 with value: 0.8221838176281153.
[I 2026-05-18 08:26:22,741] Trial 1 finished with value: 1.0015794300883971 and parameters: {'n_estimators': 908, 'max_depth': 4, 'min_samples_split': 12, 'min_samples_leaf': 7, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 0 with value: 0.8221838176281153.
[I 2026-05-18 08:26:30,847] Trial 2 finished with value: 0.8430339153582543 and parameters: {'n_estimators': 632, 'max_depth': 6, 'min_samples_split': 8, 'min_samples_leaf': 2, 'max_features': None, 'bootstrap': True}. Best is trial 0 with value: 0.8221838176281153.
[I 2026-05-18 08:26:43,536] Trial 3 finished with value: 0.81372238141277 and parameters: {'n_estimators': 714, 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 5, 'max_features': None, 'bootstrap': True}. Best is trial 3 with value: 0.81372238141277.
[I 2026-05-18 08:26:45,367] Trial 4 finished with value: 1.0028749541565927 and parameters: {'n_estimators': 504, 'max_depth': 4, 'min_samples_split': 9, 'min_samples_leaf': 4, 'max_features': 'log2', 'bootstrap': True}. Best is trial 3 with value: 0.81372238141277.
[I 2026-05-18 08:26:49,622] Trial 5 finished with value: 0.9174785627982592 and parameters: {'n_estimators': 863, 'max_depth': 6, 'min_samples_split': 7, 'min_samples_leaf': 5, 'max_features': 'log2', 'bootstrap': True}. Best is trial 3 with value: 0.81372238141277.
[I 2026-05-18 08:27:18,671] Trial 6 finished with value: 0.7974511828051216 and parameters: {'n_estimators': 798, 'max_depth': 12, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': None, 'bootstrap': False}. Best is trial 6 with value: 0.7974511828051216.
[I 2026-05-18 08:27:27,594] Trial 7 finished with value: 0.8430682003994515 and parameters: {'n_estimators': 557, 'max_depth': 6, 'min_samples_split': 7, 'min_samples_leaf': 2, 'max_features': None, 'bootstrap': True}. Best is trial 6 with value: 0.7974511828051216.
[I 2026-05-18 08:27:30,442] Trial 8 finished with value: 0.827209850115484 and parameters: {'n_estimators': 205, 'max_depth': 11, 'min_samples_split': 9, 'min_samples_leaf': 6, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 6 with value: 0.7974511828051216.
[I 2026-05-18 08:27:34,511] Trial 9 finished with value: 0.9189587933666078 and parameters: {'n_estimators': 823, 'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 3, 'max_features': 'log2', 'bootstrap': True}. Best is trial 6 with value: 0.7974511828051216.
[I 2026-05-18 08:27:37,595] Trial 10 finished with value: 0.8408558661594862 and parameters: {'n_estimators': 319, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 6 with value: 0.7974511828051216.
[I 2026-05-18 08:27:39,336] Trial 11 finished with value: 1.0001129594605331 and parameters: {'n_estimators': 307, 'max_depth': 4, 'min_samples_split': 9, 'min_samples_leaf': 3, 'max_features': 'log2', 'bootstrap': False}. Best is trial 6 with value: 0.7974511828051216.
[I 2026-05-18 08:27:41,227] Trial 12 finished with value: 1.0011963283179393 and parameters: {'n_estimators': 429, 'max_depth': 4, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 6 with value: 0.7974511828051216.
[I 2026-05-18 08:27:46,646] Trial 13 finished with value: 0.8199484733186597 and parameters: {'n_estimators': 386, 'max_depth': 12, 'min_samples_split': 7, 'min_samples_leaf': 7, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 6 with value: 0.7974511828051216.
[I 2026-05-18 08:28:05,615] Trial 14 finished with value: 0.827448222695525 and parameters: {'n_estimators': 1018, 'max_depth': 11, 'min_samples_split': 2, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 6 with value: 0.7974511828051216.
[I 2026-05-18 08:28:13,168] Trial 15 finished with value: 0.8673651092541462 and parameters: {'n_estimators': 523, 'max_depth': 8, 'min_samples_split': 9, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 6 with value: 0.7974511828051216.
[I 2026-05-18 08:28:22,681] Trial 16 finished with value: 0.8972653389368482 and parameters: {'n_estimators': 485, 'max_depth': 4, 'min_samples_split': 8, 'min_samples_leaf': 5, 'max_features': None, 'bootstrap': True}. Best is trial 6 with value: 0.7974511828051216.
[I 2026-05-18 08:28:37,490] Trial 17 finished with value: 0.8183550335234593 and parameters: {'n_estimators': 689, 'max_depth': 12, 'min_samples_split': 4, 'min_samples_leaf': 6, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 6 with value: 0.7974511828051216.
[I 2026-05-18 08:28:50,889] Trial 18 finished with value: 0.8686389170986942 and parameters: {'n_estimators': 834, 'max_depth': 8, 'min_samples_split': 2, 'min_samples_leaf': 7, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 6 with value: 0.7974511828051216.
[I 2026-05-18 08:28:53,692] Trial 19 finished with value: 0.869955818274894 and parameters: {'n_estimators': 216, 'max_depth': 8, 'min_samples_split': 4, 'min_samples_leaf': 6, 'max_features': 'log2', 'bootstrap': True}. Best is trial 6 with value: 0.7974511828051216.
[I 2026-05-18 08:29:05,920] Trial 20 finished with value: 0.8579511253170913 and parameters: {'n_estimators': 541, 'max_depth': 5, 'min_samples_split': 12, 'min_samples_leaf': 8, 'max_features': None, 'bootstrap': True}. Best is trial 6 with value: 0.7974511828051216.
[I 2026-05-18 08:29:11,090] Trial 21 finished with value: 1.0015966861735472 and parameters: {'n_estimators': 442, 'max_depth': 4, 'min_samples_split': 11, 'min_samples_leaf': 8, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 6 with value: 0.7974511828051216.
[I 2026-05-18 08:29:32,528] Trial 22 finished with value: 0.8254557788356022 and parameters: {'n_estimators': 1087, 'max_depth': 11, 'min_samples_split': 9, 'min_samples_leaf': 1, 'max_features': 'log2', 'bootstrap': False}. Best is trial 6 with value: 0.7974511828051216.
[I 2026-05-18 08:29:39,110] Trial 23 finished with value: 1.0012738773465337 and parameters: {'n_estimators': 864, 'max_depth': 4, 'min_samples_split': 3, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 6 with value: 0.7974511828051216.
[I 2026-05-18 08:29:46,778] Trial 24 finished with value: 0.8418570162126101 and parameters: {'n_estimators': 525, 'max_depth': 10, 'min_samples_split': 9, 'min_samples_leaf': 7, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 6 with value: 0.7974511828051216.
[I 2026-05-18 08:29:53,701] Trial 25 finished with value: 0.8246790756338355 and parameters: {'n_estimators': 444, 'max_depth': 12, 'min_samples_split': 6, 'min_samples_leaf': 8, 'max_features': 'log2', 'bootstrap': True}. Best is trial 6 with value: 0.7974511828051216.
[I 2026-05-18 08:30:07,407] Trial 26 finished with value: 0.8032501856402651 and parameters: {'n_estimators': 395, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': None, 'bootstrap': True}. Best is trial 6 with value: 0.7974511828051216.
[I 2026-05-18 08:30:12,280] Trial 27 finished with value: 1.0037095894968968 and parameters: {'n_estimators': 570, 'max_depth': 4, 'min_samples_split': 12, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 6 with value: 0.7974511828051216.
[I 2026-05-18 08:30:25,495] Trial 28 finished with value: 0.9177527671265484 and parameters: {'n_estimators': 1051, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 6 with value: 0.7974511828051216.
[I 2026-05-18 08:30:37,840] Trial 29 finished with value: 0.9564396407649186 and parameters: {'n_estimators': 1191, 'max_depth': 5, 'min_samples_split': 7, 'min_samples_leaf': 8, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 6 with value: 0.7974511828051216.
[I 2026-05-18 08:31:32,533] Trial 30 finished with value: 0.8075541683343815 and parameters: {'n_estimators': 1010, 'max_depth': 11, 'min_samples_split': 11, 'min_samples_leaf': 8, 'max_features': None, 'bootstrap': False}. Best is trial 6 with value: 0.7974511828051216.
[I 2026-05-18 08:31:54,775] Trial 31 finished with value: 0.8169795784345545 and parameters: {'n_estimators': 996, 'max_depth': 12, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': 'log2', 'bootstrap': False}. Best is trial 6 with value: 0.7974511828051216.
[I 2026-05-18 08:32:03,867] Trial 32 finished with value: 0.8510237927822882 and parameters: {'n_estimators': 486, 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 6 with value: 0.7974511828051216.
[I 2026-05-18 08:32:26,518] Trial 33 finished with value: 0.8166552798775769 and parameters: {'n_estimators': 416, 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': None, 'bootstrap': False}. Best is trial 6 with value: 0.7974511828051216.
[I 2026-05-18 08:32:39,927] Trial 34 finished with value: 0.9178012583659866 and parameters: {'n_estimators': 716, 'max_depth': 6, 'min_samples_split': 10, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 6 with value: 0.7974511828051216.
[I 2026-05-18 08:33:19,114] Trial 35 finished with value: 0.8318306621424689 and parameters: {'n_estimators': 896, 'max_depth': 7, 'min_samples_split': 3, 'min_samples_leaf': 2, 'max_features': None, 'bootstrap': True}. Best is trial 6 with value: 0.7974511828051216.
[I 2026-05-18 08:33:39,438] Trial 36 finished with value: 0.8396173933265703 and parameters: {'n_estimators': 1155, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 6 with value: 0.7974511828051216.
[I 2026-05-18 08:33:42,641] Trial 37 finished with value: 0.9987796569241042 and parameters: {'n_estimators': 316, 'max_depth': 4, 'min_samples_split': 2, 'min_samples_leaf': 7, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 6 with value: 0.7974511828051216.
[I 2026-05-18 08:33:47,551] Trial 38 finished with value: 0.8885606041526057 and parameters: {'n_estimators': 373, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 6 with value: 0.7974511828051216.
[I 2026-05-18 08:34:05,838] Trial 39 finished with value: 0.8512804338368792 and parameters: {'n_estimators': 1057, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 6 with value: 0.7974511828051216.
[I 2026-05-18 08:34:28,682] Trial 40 finished with value: 0.8137934863096036 and parameters: {'n_estimators': 588, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 5, 'max_features': None, 'bootstrap': True}. Best is trial 6 with value: 0.7974511828051216.
[I 2026-05-18 08:34:31,785] Trial 41 finished with value: 0.9999965516898887 and parameters: {'n_estimators': 269, 'max_depth': 4, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True}. Best is trial 6 with value: 0.7974511828051216.
[I 2026-05-18 08:34:44,806] Trial 42 finished with value: 0.9166412590537335 and parameters: {'n_estimators': 1015, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 6, 'max_features': 'log2', 'bootstrap': True}. Best is trial 6 with value: 0.7974511828051216.
[I 2026-05-18 08:35:04,743] Trial 43 finished with value: 0.812795844913768 and parameters: {'n_estimators': 377, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 8, 'max_features': None, 'bootstrap': False}. Best is trial 6 with value: 0.7974511828051216.
[I 2026-05-18 08:35:19,684] Trial 44 finished with value: 0.8890405692391692 and parameters: {'n_estimators': 1059, 'max_depth': 7, 'min_samples_split': 10, 'min_samples_leaf': 7, 'max_features': 'log2', 'bootstrap': True}. Best is trial 6 with value: 0.7974511828051216.
[I 2026-05-18 08:35:56,916] Trial 45 finished with value: 0.8330116377742295 and parameters: {'n_estimators': 1096, 'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 8, 'max_features': None, 'bootstrap': True}. Best is trial 6 with value: 0.7974511828051216.
[I 2026-05-18 08:36:28,508] Trial 46 finished with value: 0.8219564043185212 and parameters: {'n_estimators': 832, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': None, 'bootstrap': True}. Best is trial 6 with value: 0.7974511828051216.
[I 2026-05-18 08:36:34,746] Trial 47 finished with value: 1.0023892908256562 and parameters: {'n_estimators': 694, 'max_depth': 4, 'min_samples_split': 8, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'bootstrap': False}. Best is trial 6 with value: 0.7974511828051216.
[I 2026-05-18 08:36:41,833] Trial 48 finished with value: 1.0020049143328182 and parameters: {'n_estimators': 818, 'max_depth': 4, 'min_samples_split': 2, 'min_samples_leaf': 6, 'max_features': 'log2', 'bootstrap': False}. Best is trial 6 with value: 0.7974511828051216.
[I 2026-05-18 08:36:56,130] Trial 49 finished with value: 0.8889919707793048 and parameters: {'n_estimators': 1187, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 7, 'max_features': 'log2', 'bootstrap': True}. Best is trial 6 with value: 0.7974511828051216.
[I 2026-05-18 08:37:51,055] Trial 50 finished with value: 0.8075509280411284 and parameters: {'n_estimators': 1031, 'max_depth': 11, 'min_samples_split': 11, 'min_samples_leaf': 8, 'max_features': None, 'bootstrap': False}. Best is trial 6 with value: 0.7974511828051216.
[I 2026-05-18 08:38:27,619] Trial 51 finished with value: 0.8075586749498002 and parameters: {'n_estimators': 635, 'max_depth': 11, 'min_samples_split': 12, 'min_samples_leaf': 8, 'max_features': None, 'bootstrap': False}. Best is trial 6 with value: 0.7974511828051216.
[I 2026-05-18 08:39:16,961] Trial 52 finished with value: 0.8064454432235917 and parameters: {'n_estimators': 864, 'max_depth': 12, 'min_samples_split': 12, 'min_samples_leaf': 8, 'max_features': None, 'bootstrap': False}. Best is trial 6 with value: 0.7974511828051216.
[I 2026-05-18 08:40:04,061] Trial 53 finished with value: 0.8077362543022516 and parameters: {'n_estimators': 875, 'max_depth': 11, 'min_samples_split': 12, 'min_samples_leaf': 6, 'max_features': None, 'bootstrap': False}. Best is trial 6 with value: 0.7974511828051216.
[I 2026-05-18 08:40:52,602] Trial 54 finished with value: 0.7963173785278407 and parameters: {'n_estimators': 830, 'max_depth': 12, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': None, 'bootstrap': False}. Best is trial 54 with value: 0.7963173785278407.
[I 2026-05-18 08:41:47,478] Trial 55 finished with value: 0.7974603713369579 and parameters: {'n_estimators': 968, 'max_depth': 12, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': None, 'bootstrap': False}. Best is trial 54 with value: 0.7963173785278407.
[I 2026-05-18 08:42:36,169] Trial 56 finished with value: 0.7959338341913108 and parameters: {'n_estimators': 853, 'max_depth': 12, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': None, 'bootstrap': False}. Best is trial 56 with value: 0.7959338341913108.
[I 2026-05-18 08:43:24,556] Trial 57 finished with value: 0.8005961988844976 and parameters: {'n_estimators': 892, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': None, 'bootstrap': False}. Best is trial 56 with value: 0.7959338341913108.
[I 2026-05-18 08:44:09,580] Trial 58 finished with value: 0.7963182798857555 and parameters: {'n_estimators': 774, 'max_depth': 12, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': None, 'bootstrap': False}. Best is trial 56 with value: 0.7959338341913108.
[I 2026-05-18 08:44:58,270] Trial 59 finished with value: 0.7974506046772502 and parameters: {'n_estimators': 822, 'max_depth': 12, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': None, 'bootstrap': False}. Best is trial 56 with value: 0.7959338341913108.
Best Trial: 56
Best MAE: 0.7959338341913108
Best Parameters:
    n_estimators: 853
    max_depth: 12
    min_samples_split: 4
    min_samples_leaf: 1
    max_features: None
    bootstrap: False

RandomForestRegressor(bootstrap=False, max_depth=12, max_features=None,
                      min_samples_split=4, n_estimators=853, n_jobs=-1,
                      random_state=42)

In [5]:
test_pred = final_model.predict(X_test_imputed)
test_mae = mean_absolute_error(y_test, test_pred)

print(f"\nFinal Test MAE: {test_mae:.4f}")
print(f"Number of trees used: {final_model.n_estimators}")

Final Test MAE: 0.8112
Number of trees used: 853

In [6]:
import os
import joblib
# Delete old model before training
if os.path.exists("/models/pump_time/random_forest_model.ubj"):
    os.remove("/models/pump_time/random_forest_model.ubj")
    print("Old model deleted")

joblib.dump(final_model,"/workspace/models/pump_time/random_forest_model.ubj")
print("\nModel saved.")

Model saved.